## default settings.
FP       ?= 32

## Compiler

## NVIDIA Compiler version 24.1 or former
CXX = nvc++ -std=c++17 -mp=gpu -gpu=managed
CC  = nvc              -mp=gpu -gpu=managed
F90 = nvfortran -cpp   -mp=gpu -gpu=managed

## NVIDIA Compiler version 24.5 or later
#CXX = nvc++ -std=c++17 -mp=gpu -gpu=mem:managed
#CC  = nvc              -mp=gpu -gpu=mem:managed
#F90 = nvfortran -cpp   -mp=gpu -gpu=mem:managed

## Compile Options
FLAGS = -tp=native -O3 -I. -Wall -Minfo=accel,opt,mp
FFLAGS = -Imod -module mod

# floating point type
FLAGS += -DFP=$(FP)

# for benchmarking
FLAGS += -DBENCHMARK_MODE

## Additional C++ Library for Fortran90 Programs
#LIBS += -lstdc++

##---------------------------------------------------------------------------
## Make rules
TARGET = diffusion.gpu.$(FP)

OBJS = misc.o diffusion.o main.o

all: show_config $(TARGET)

.SUFFIXES:
.SUFFIXES: .cpp .c .f90 .o

%.o: %.c	
	$(CC)  -c $(FLAGS) $< -o $@

%.o: %.cpp
	$(CXX) -c $(FLAGS) $< -o $@

%.o: %.f90
	mkdir -p mod
	$(F90) -c $(FLAGS) $(FFLAGS) $< -o $@

$(TARGET): $(OBJS)
#	$(CXX) $(OBJS) $(LIBS) -o $@
#	$(CC)  $(OBJS) $(LIBS) -o $@
	$(F90) $(OBJS) $(LIBS) -o $@

install: $(TARGET)
	mkdir -p ../bin ../log
	cp -f  $(TARGET) ../bin

clean:
	rm -f $(TARGET) *.o */*.mod *~

show_config:
	@echo "======================================"
	@echo "GPU FP=$(FP)                          "
	@echo "======================================"

main.o: diffusion.f90 misc.f90
diffusion.o: misc.f90
misc.o: misc.f90
