## default settings.
FP       ?= 32
NTHREADS ?= 128

## Compiler

## NVIDIA Compiler version 24.1 or former
#CXX = nvc++ -std=c++17 -mp -acc=gpu -gpu=managed
#CC  = nvc              -mp -acc=gpu -gpu=managed
#F90 = nvfortran -cpp   -mp -acc=gpu -gpu=managed

## NVIDIA Compiler version 24.5 or later
CXX = nvc++ -std=c++17 -mp -acc=gpu -gpu=mem:managed
CC  = nvc              -mp -acc=gpu -gpu=mem:managed
F90 = nvfortran -cpp   -mp -acc=gpu -gpu=mem:managed

## Compile Options
FLAGS = -tp=native -O3 -I. -Wall -Minfo=accel,opt,mp
FFLAGS = -Imod -module mod

# floating point type
FLAGS += -DFP=$(FP)

# for benchmarking
FLAGS += -DBENCHMARK_MODE

# for finding the best threads
FLAGS += -DNTHREADS=$(NTHREADS)

## Additional C++ Library for Fortran90 Programs
#LIBS += -lstdc++

##---------------------------------------------------------------------------
## Make rules
#TARGET = diffusion.gpu.$(FP).$(NTHREADS)
TARGET = diffusion.gpu.$(FP)

OBJS = misc.o diffusion.o main.o

all: show_config $(TARGET)

.SUFFIXES:
.SUFFIXES: .cpp .c .f90 .o

%.o: %.c	
	$(CC)  -c $(FLAGS) $< -o $@

%.o: %.cpp
	$(CXX) -c $(FLAGS) $< -o $@

%.o: %.f90
	mkdir -p mod
	$(F90) -c $(FLAGS) $(FFLAGS) $< -o $@

$(TARGET): $(OBJS)
#	$(CXX) $(OBJS) $(LIBS) -o $@
	$(CC)  $(OBJS) $(LIBS) -o $@
#	$(F90) $(OBJS) $(LIBS) -o $@

install: $(TARGET)
	mkdir -p ../bin ../log
	cp -f  $(TARGET) ../bin

clean:
	rm -f $(TARGET) *.o */*.mod *~

show_config:
	@echo "======================================"
	@echo "GPU FP=$(FP) NTHREADS=$(NTHREADS)     "
	@echo "======================================"

main.o: diffusion.h misc.h
diffusion.o: misc.h
misc.o: misc.h
